import { Values } from './values'

export const CAMERA_PERMISSION_TITLE = 'O acesso à camera é necessário'
export const CAMERA_PERMISSION_MESSAGE = 'Você precisa conceder acesso à camera para poder bater ponto e checar seu histórico'

export const SIGN_UP_PHOTO_FAIL_TITLE = 'Erro de identificação'
export const SIGN_UP_PHOTO_FAIL_DESCRIPTION = 'Não conseguimos te identificar na foto'
export const SIGN_ID_MISMATCH_IMAGE_TITLE = 'Parece que este não é você'
export const SIGN_ID_MISMATCH_IMAGE_DESCRIPTION = 'Sua foto não corresponde à matricula. Verifique se você inseriu sua matrícula correta. Se o problema persistir, entre em contato com o RH'
export const CLOCK_IN_SUCCESS_TITLE = 'Ponto registrado'
export const CLOCK_IN_SUCCESS_DESCRIPTION = 'Sua foto foi identificada e seu ponto foi registrado com sucesso'
export const CLOCK_IN_FAIL_TITLE = 'Erro ao registrar ponto'
export const CLOCK_IN_FAIL_DESCRIPTION = 'Ocorreu um erro ao registar o ponto'
export const NO_PERSON_ON_IMAGE_TITLE = 'Não achamos ninguém na foto'
export const NO_PERSON_ON_IMAGE_DESCRIPTION = 'Tente se posicionar mais ao centro da imagem'
export const TOO_MUCH_PERSON_ON_IMAGE_TITLE = 'Existe mais de uma pessoa na foto'
export const TOO_MUCH_PERSON_ON_IMAGE_DESCRIPTION = 'Mais de uma pessoa foi reconhecida na foto, tente tirar a foto sozinho'
export const USER_RECOGNITION_FAIL_TITLE = 'Erro de identificação'
export const USER_RECOGNITION_FAIL_DESCRIPTION = 'Não conseguimos te identificar na foto. Tente melhorar a identificação para obter melhores resultados'
export const HELP_MODAL_TITLE = 'Precisa de ajuda?'
export const HELP_MODAL_DESCRIPTION = `Ligue para ${Values.HELP_PHONE.STRING} e acesse a opção 2 que iremos te ajudar`
export const HELP_MODAL_ACTION_LABEL = 'Ligar'
export const TRAIN_PHOTO_SUCCESS_TITLE = 'Melhoria registrada'
export const TRAIN_PHOTO_SUCCESS_DESCRIPTION = 'Foto registrada para melhor reconhecimento'
export const IP_VALIDATION_FAIL_TITLE = 'IP não reconhecido'
export const IP_VALIDATION_FAIL_DESCRIPTION = 'Verifique se você está conectado à rede correta'

export const VERIFY_USER_FAIL_TITLE = 'Funcionário não encontrado, verifique se você digitou sua matrícula correta'

export const ERROR_NO_PERSON_ON_IMAGE = 'Rosto não reconhecido'
export const ERROR_TOO_MUCH_PERSON_ON_IMAGE = 'Mais de uma pessoa na foto'
export const ERROR_ID_MISMATCH_IMAGE = 'Foto não corresponde à matrícula do funcionário'
