import Config from 'react-native-config'

const {
  BASE_URL,
  KAIROS_BASE_URL,
  KAIROS_API_ID,
  KAIROS_API_KEY,
  KAIROS_SCHOOL_GALERY_NAME,
  IP_ADDRESS_API
} = Config

export const Values = {
  API_URL: BASE_URL,
  KAIROS_API_URL: KAIROS_BASE_URL,
  KAIROS_API_ID,
  KAIROS_API_KEY,
  KAIROS_SCHOOL_GALERY_NAME,
  IP_ADDRESS_API
}
